apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-logging
  labels:
    app: python-logging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-logging
  template:
    metadata:
      labels:
        app: python-logging
    spec:
      containers:
      - name: python-logging
        image: gcr.io/stackdriver-kubernetes/python-logging:latest
        ports:
        - containerPort: 5000